[book]
authors = ["Dabb1e"]
language = "en"
multilingual = false
src = "docs"
title = "Impulse"

[output.html]
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-alerts.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"

[preprocessor.alerts]
